name: artifact

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - 'x86_64-linux'
          - 'aarch64-linux'
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          init: systemd

      - name: Configure Nix for CI
        run: |
            echo "max-jobs = auto" | sudo tee -a /etc/nix/nix.conf
            echo "cores = 0" | sudo tee -a /etc/nix/nix.conf
            echo "sandbox = false" | sudo tee -a /etc/nix/nix.conf
            sudo systemctl restart nix-daemon

      - name: Building tarball for ${{ matrix.arch }}
        run: nix build

      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nixos-system-${{ matrix.arch }}.tar.xz
          path: result/tarball/nixos-system-${{ matrix.arch }}.tar.xz
